### PR TITLE
Convert to octave-based MAT reader

### PR DESCRIPTION
**Pull request by gdevenyi**
Resubmit against develop

### CODE REVIEW

**Comment by gdevenyi** [comment]
I'd like to integrate this with ana2mnc_xfm_reduce.pl but #39 currently prevents me

**Comment by gdevenyi** [comment]
@andrewjanke just to reiterate my question, I wanted to make sure that octave's display command printed the matrix the same way mat1dump is doing so, so your parsing will handle it properly.

**Comment by gdevenyi** [comment]
i.e. this is octave's output:

```
$ spm_show 1001794_wba_001.mat
    -0.46875     0.00000     0.00000   120.46875
     0.00000    -0.46875     0.00000   136.83240
     0.00000     0.00000     1.50000   -66.20751
     0.00000     0.00000     0.00000     1.00000
```

**Comment by vfonov** [comment]
How does  itk_convert_xfm behave in this situation ?

**Comment by andrewjanke** [comment]
@vfonov probably does exactly the same thing (But better!) I wasn't aware of it but no doubt you wrote it to solve the same problem.

**Comment by gdevenyi** [comment]
@vfonov 

```
itk_convert_xfm 1001794_wba_001.mat /tmp/itk.xfm
Transform reader for 1001794_wba_001.mat caught an ITK exception:

itk::ExceptionObject (0x1ef4bd0)
Location: "unknown" 
File: /opt/quarantine/minc-toolkit/git/src/build/ITKv4/Modules/IO/TransformMatlab/include/itkMatlabTransformIO.hxx
Line: 107
Description: itk::ERROR: MatlabTransformIOTemplate(0x1ef4bf0): Only vector parameters supported

Can't read:1001794_wba_001.mat

```

**Pull request merged**
