### PR TITLE
Make major modifications to dcm2mnc towards better support of a variety of datasets

### PR DESCRIPTION
**Pull request by jpcoutu**
Better conversion support of various PET datasets, multi-echo acquisitions, mosaic DICOM datasets, GEMS diffusion MRI datasets, Philips ASL datasets, Siemens private headers, slice order of fMRI datasets, RealWorldValue rescaling and Philips private header quantitative rescaling.

As mentioned on the MINC-development mailing list, this is the result of 4 years of internal development on dcm2mnc (with contributions from Massine Yahia, Dany Chagnon, Jiaxing Li and others) that we couldn't feed back in a more piecemeal approach. This fixes a wide range of issues, and offering this as take it or leave it, but happy to answer questions, and feel free to modify as you see fit.

### CODE REVIEW

**Comment by vfonov** [comment]
Thank you for the contribution! 
Do you happen to have examples of the dicom files that are now supported ? Even better would be to add some unit tests for dcm2mnc

**Comment by jpcoutu** [comment]
Unfortunately the DICOM data and associated unit/regression tests are proprietary and we are unable to share them.

**Comment by vfonov** [comment]
Well, this change did not help with the sample dataset I got from @cmadjar:
output of old version on the left, new version is on the right. 

Screenshot at 2021-05-18 23-27-40

Screenshot from 2021-05-18 23-49-24

**Comment by vfonov** [comment]
I don't feel comfortable making a big change to the crucial minc tool without proper testing. Currently there are no tests for dcm2mnc. I started building a dataset of DICOM images that could be used for testing , but it is taking time. 
So, I suggest that interested parties, @cmadjar for example, help in creating a test suite for this tool.

**Comment by jpcoutu** [comment]
I looked again through our internal regression test dataset and a small subset of data we use are public and can be found here if that helps (not only under that section, but elsewhere on that page as well):
https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Archival_MRI
However, I don't recall if we ended up fixing dcm2mnc to handle some of these, or whether we simply used it to make sure we did not introduce any bugs.

**Comment by vfonov** [comment]
Having a dataset to test is good, now somebody actually have to make regression tests.

**Comment by jpcoutu** [comment]
Closing this PR as it does introduce issues with the existing multi-frame conversion. We have corrected those issues internally and improved support for multi-frame conversion. I can open a new PR if desired but it would come with the same caveat as before, without test data, and with more changes than this PR.

**Comment by vfonov** [comment]
well, create a pull request, maybe sometime in the future somebody will create a proper test set to run regression tests.

**Pull request closed without merging**
