### PR TITLE
Add label handling to minclookup to prevent renormalization

### PR DESCRIPTION
**Pull request by gdevenyi**
Compiles and works, labels are no longer renormalized.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Fixes #91

**Review by vfonov — COMMENTED** [review]
Looks ok, do we need a test case for that?

**Comment by gdevenyi** [comment]
I'll take a look at the tests you added for the other "-label" options you added.

**Comment by gdevenyi** [comment]
Tests added

**Pull request merged**
